# Generated by Django 3.2 on 2021-04-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=128)),
                ('revision', models.BigIntegerField()),
                ('document_class_id', models.CharField(max_length=16)),
                ('object_id', models.TextField(db_index=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
