# Generated by Django 3.2 on 2021-05-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='document_id',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='change',
            name='revision',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterIndexTogether(
            name='change',
            index_together={('document_id', 'revision')},
        ),
        migrations.RemoveField(
            model_name='change',
            name='document_class_id',
        ),
        migrations.RemoveField(
            model_name='change',
            name='object_id',
        ),
    ]
