# Generated by Django 3.2 on 2021-10-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofa', '0006_auto_20211020_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replicationhistory',
            name='session_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='replicationlog',
            name='replicator',
            field=models.CharField(max_length=64),
        ),
    ]
